### ISSUE TITLE
ServerException in RequestException

### ISSUE THREAD

**Issue by hifiaz** [itsmeabde/tiket-api#2]
<img width="996" alt="screen shot 2016-11-15 at 5 22 53 pm" src="https://cloud.githubusercontent.com/assets/20653803/20308010/b3f32a80-ab74-11e6-9822-c8ff2da880c7.png">
kayaknya ada yang salah ketika memasukkan kata kunci/query. Bagaimana penyelesaiannya?

**Comment by itsmeabde** [comment]
Itu errornya parameternya, yg mas masukan ada yg salah atau g valid.
documentasinya di http://docs.tiket.com. disitu lengkap nama parameter yg dibutuhkan mas.

![ex_params](https://cloud.githubusercontent.com/assets/21280766/20313988/4f3807c0-ab8b-11e6-8461-9a1569a328de.jpg)

**Comment by hifiaz** [comment]
makasih mas, bisa minta tolong kasih contoh penulisannya?
